# Data Preparation

## Imports

In [43]:
import pandas as pd

## Limpieza

In [44]:
df = pd.read_csv('data/H-AIRosettaMP.csv')

In [45]:
df = df.dropna()
df = df.drop(columns=["task_url", "task_description"])
df.drop_duplicates(subset=['code'], inplace=True)

In [46]:
df.head()

,task_name,language_name,code,target,set
0,Array concatenation,Java,import java.util.Vector;\nimport java.util.Ite...,Ai_generated,Java_from_C++
1,Array length,Java,public class Main {\n public static void ma...,Ai_generated,Java_from_C++
2,Arithmetic/Integer,Java,import java.util.Scanner;\n\npublic class Main...,Ai_generated,Java_from_C++
3,Arithmetic-geometric mean/Calculate Pi,Java,import java.math.BigDecimal;\nimport java.math...,Ai_generated,Java_from_C++
4,Arithmetic/Rational,Java,import java.math.BigInteger;\nimport java.util...,Ai_generated,Java_from_C++

In [47]:
lenguajes = ['Python', 'Java', 'JavaScript', 'C++', 'cpp']

df_filtrado = df[df['language_name'].isin(lenguajes)]

df_filtrado = df_filtrado[df_filtrado['set'].str.endswith(tuple(lenguajes))]

tareas_con_humano = df_filtrado[df_filtrado['target'] == 'Human_written'][['task_name', 'language_name']].drop_duplicates()

df_final = df_filtrado.merge(tareas_con_humano, on=['task_name', 'language_name'], how='inner')

print(df_final['target'].value_counts())
print(df_final['language_name'].value_counts())

target
Ai_generated     7456
Human_written    3420
Name: count, dtype: int64
language_name
Python        2971
Java          2868
cpp           2747
JavaScript    2290
Name: count, dtype: int64

In [48]:
humans = df_final[df_final['target'] == 'Human_written']
ia = df_final[df_final['target'] == 'Ai_generated']

print(humans['language_name'].value_counts())
print(ia['language_name'].value_counts())

language_name
Python        957
Java          920
cpp           875
JavaScript    668
Name: count, dtype: int64
language_name
Python        2014
Java          1948
cpp           1872
JavaScript    1622
Name: count, dtype: int64

In [49]:
ia2 = ia[ia['language_name'] == 'Python']
ia2.head()

,task_name,language_name,code,target,set
5615,Array concatenation,Python,"def concat(arr1, arr2):\n res = [None] * (l...",Ai_generated,Python_from_Java
5616,Arithmetic/Integer,Python,import java.util.Scanner;\n \npublic class Flo...,Ai_generated,Python_from_Java
5617,Arithmetic-geometric mean/Calculate Pi,Python,import math\nfrom decimal import *\n\ngetconte...,Ai_generated,Python_from_Java
5618,Arithmetic-geometric mean,Python,# Arithmetic-Geometric Mean of 1 & 1/sqrt(2)\n...,Ai_generated,Python_from_Java
5619,Arithmetic/Rational,Python,from fractions import Fraction\n\nMAX_NUM = 1 ...,Ai_generated,Python_from_Java

In [50]:
df_final.to_csv('data/filtered_H-AIRosettaMP.csv', index=False)

In [51]:
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 10876 entries, 0 to 10875
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   task_name      10876 non-null  str
 1   language_name  10876 non-null  str
 2   code           10876 non-null  str
 3   target         10876 non-null  str
 4   set            10876 non-null  str
dtypes: str(5)
memory usage: 425.0 KB