# EDA

### 1. Imports

In [52]:
import pandas as pd
pd.reset_option('display.max_colwidth')

### 2. Información general

In [53]:
df = pd.read_csv("data/H-AIRosettaMP.csv")

In [54]:
df.tail(5)

,task_url,task_name,task_description,language_name,code,target,set
121242,http://rosettacode.org/wiki/4-rings_or_4-squar...,4-rings or 4-squares puzzle,4-rings or 4-squares puzzle\n\nYou are encoura...,Kotlin,// version 1.1.2\n \nclass FourSquares(\n p...,Human_written,Kotlin_from_Rust
121243,http://rosettacode.org/wiki/ABC_problem,ABC problem,ABC problem\n\nYou are encouraged to solve thi...,Kotlin,object ABC_block_checker {\n fun run() {\n ...,Human_written,Kotlin_from_Rust
121244,http://rosettacode.org/wiki/24_game,24 game,The 24 Game tests one's mental arithmetic.\n\n...,Kotlin,import java.util.Random\nimport java.util.Scan...,Human_written,Kotlin_from_Rust
121245,http://rosettacode.org/wiki/100_prisoners,100 prisoners,\n\nThe Problem\n\n 100 prisoners are individu...,Kotlin,val playOptimal: () -> Boolean = {\n val se...,Human_written,Kotlin_from_Rust
121246,http://rosettacode.org/wiki/A%2BB,A+B,A+B ─── a classic problem in programming con...,Kotlin,// version 1.0.5-2\n \nfun main(args: Array<St...,Human_written,Kotlin_from_Rust

In [55]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 121247 entries, 0 to 121246
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   task_url          121247 non-null  str
 1   task_name         121247 non-null  str
 2   task_description  121195 non-null  str
 3   language_name     121247 non-null  str
 4   code              121205 non-null  str
 5   target            121247 non-null  str
 6   set               121247 non-null  str
dtypes: str(7)
memory usage: 6.5 MB

### 3. Balance de información

In [56]:
df["target"].value_counts()

target
Human_written    60624
Ai_generated     60623
Name: count, dtype: int64

In [57]:
df["language_name"].unique()

<StringArray>
[      'Java',        'cpp',     'Python', 'JavaScript',         'C#',
          'C',         'Go',       'Ruby',       'Rust',     'Kotlin']
Length: 10, dtype: str

In [58]:
df["language_name"].value_counts()

language_name
Go            13763
Python        13737
Ruby          13335
Java          12351
Kotlin        12256
cpp           12029
C             11715
C#            11331
Rust          10665
JavaScript    10065
Name: count, dtype: int64

### 4. Duplicados

In [59]:
df.dropna(inplace=True)

In [60]:
df["code"].duplicated().sum()

np.int64(52483)

In [61]:
grouped_df = df.groupby('code').agg(list).reset_index()

In [62]:
grouped_df.head(1)

,code,task_url,task_name,task_description,language_name,target,set
0,"""""""\n Compute nearest pair of points using tw...",[http://rosettacode.org/wiki/Closest-pair_prob...,"[Closest-pair problem, Closest-pair problem, C...",[\n\n This page uses content from Wikipedia. T...,"[Python, Python, Python, Python, Python]","[Human_written, Human_written, Human_written, ...","[Python_from_JavaScript, Python_from_C#, Pytho..."

In [63]:
df["task_name"].duplicated().sum()

np.int64(120027)

In [64]:
grouped = df.groupby('task_name').size()
grouped.head(20)

task_name
100 doors                             176
100 prisoners                         156
15 puzzle game                         40
15 puzzle solver                        2
21 game                                52
24 game                               126
24 game/Solve                          56
4-rings or 4-squares puzzle           146
9 billion names of God the integer    172
99 bottles of beer                     80
A+B                                   170
ABC problem                           158
AKS test for primes                   166
ASCII art diagram converter            12
AVL tree                               10
Abbreviations, automatic              166
Abbreviations, easy                   106
Abbreviations, simple                  74
Abelian sandpile model                 24
Abelian sandpile model/Identity        12
dtype: int64

### 5. Balance y duplicados en Python

In [65]:
df_python = df[df['language_name'] == 'Python']
df_python.head()

,task_url,task_name,task_description,language_name,code,target,set
24380,http://rosettacode.org/wiki/Array_concatenation,Array concatenation,Task\n\nShow how to concatenate two arrays in ...,Python,"def concat(arr1, arr2):\n res = [None] * (l...",Ai_generated,Python_from_Java
24381,http://rosettacode.org/wiki/Arithmetic/Integer,Arithmetic/Integer,\nBasic Data Operation\n\nThis is a basic data...,Python,import java.util.Scanner;\n \npublic class Flo...,Ai_generated,Python_from_Java
24382,http://rosettacode.org/wiki/Arithmetic-geometr...,Arithmetic-geometric mean/Calculate Pi,Almkvist Berndt 1988 begins with an investigat...,Python,import math\nfrom decimal import *\n\ngetconte...,Ai_generated,Python_from_Java
24383,http://rosettacode.org/wiki/Arithmetic-geometr...,Arithmetic-geometric mean,\n\n This page uses content from Wikipedia. Th...,Python,# Arithmetic-Geometric Mean of 1 & 1/sqrt(2)\n...,Ai_generated,Python_from_Java
24384,http://rosettacode.org/wiki/Arithmetic/Rational,Arithmetic/Rational,Task\n\nCreate a reasonably complete implement...,Python,from fractions import Fraction\n\nMAX_NUM = 1 ...,Ai_generated,Python_from_Java

In [66]:
df_python.info()

<class 'pandas.DataFrame'>
Index: 13718 entries, 24380 to 38116
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   task_url          13718 non-null  str
 1   task_name         13718 non-null  str
 2   task_description  13718 non-null  str
 3   language_name     13718 non-null  str
 4   code              13718 non-null  str
 5   target            13718 non-null  str
 6   set               13718 non-null  str
dtypes: str(7)
memory usage: 857.4 KB

In [72]:
df["target"].value_counts()

target
Human_written    60590
Ai_generated     60563
Name: count, dtype: int64

In [71]:
df_python["code"].duplicated().sum()

np.int64(5843)